kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: k8s-event-tailer

rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: k8s-event-tailer

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-event-tailer

subjects:
  - kind: ServiceAccount
    namespace: k8s-event-tailer
    name: k8s-event-tailer